name: Deploy to Google Container Registry and Firestore Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Tag, Push Docker Images, Deploy Firestore Function, and Terraform
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Google Container Registry (GCR)
      - name: Log in to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      # Step 4: Build and push Docker images
      - name: Build and push Docker images
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/firestore-endpoint:${{ github.sha }} ./endpoints/firestore-endpoint
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/https-endpoint:${{ github.sha }} ./endpoints/https-endpoint
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/scheduler-endpoint:${{ github.sha }} ./endpoints/scheduler-endpoint
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/firestore-endpoint:${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/https-endpoint:${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/scheduler-endpoint:${{ github.sha }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
        # Auth via gcloud using the service account key
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate to Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > $HOME/gcloud-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # Step 8: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      # Step 9: Terraform Init
      - name: Terraform Init
        working-directory: terraform/
        run: terraform init

      # Step 10: Terraform Validate
      - name: Terraform Validate
        working-directory: terraform/
        run: terraform validate

      # Step 11: Terraform Plan
      - name: Terraform Plan
        working-directory: terraform/
        run: terraform plan -out ./plan.tfplan

      # Step 12: Terraform Apply
      - name: Terraform Apply
        working-directory: terraform/
        run: terraform apply -auto-approve
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      # Step 5: Set up Node.js (for Firebase CLI)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
    
      # Step 6: Install dependencies for Firebase functions
      - name: Install Firebase function dependencies
        working-directory: endpoints/firestore-endpoint/trigger-functions/functions
        run: npm install
    
      # Step 7: Deploy Firebase Functions
      - name: Deploy Firebase Functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }}
