name: Deploy to Google Container Registry and Firestore Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Tag, Push Docker Images, Deploy Firestore Function, and Terraform
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Google Container Registry (GCR)
      - name: Log in to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      # Step 4: Build and push Docker images
      - name: Build and push Docker images
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/firestore-endpoint:${{ github.sha }} ./endpoints/firestore-endpoint
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/https-endpoint:${{ github.sha }} ./endpoints/https-endpoint
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/scheduler-endpoint:${{ github.sha }} ./endpoints/scheduler-endpoint
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/firestore-endpoint:${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/https-endpoint:${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/scheduler-endpoint:${{ github.sha }}

      # Step 5: Set up Node.js (for Firebase CLI)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Step 6: Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Step 7: Deploy Firestore trigger function
      - name: Deploy Firestore Function
        working-directory: ./endpoints/firestore-endpoint/trigger-functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Ensure FIREBASE_TOKEN is set in your GitHub Secrets
        run: firebase deploy --only functions

      # Step 8: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      # Step 9: Terraform Init
      - name: Terraform Init
        working-directory: terraform/
        run: terraform init

      # Step 10: Terraform Validate
      - name: Terraform Validate
        working-directory: terraform/
        run: terraform validate

      # Step 11: Terraform Plan
      - name: Terraform Plan
        working-directory: terraform/
        run: terraform plan -out ./plan.tfplan

      # Step 12: Terraform Apply
      - name: Terraform Apply
        working-directory: terraform/
        run: terraform apply -auto-approve
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
