name: Deploy to Google Container Registry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Tag, and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker images
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/firestore-endpoint:${{ github.sha }} ./endpoints/firestore-endpoint
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/https-endpoint:${{ github.sha }} ./endpoints/https-endpoint
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/scheduler-endpoint:${{ github.sha }} ./endpoints/scheduler-endpoint
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/firestore-endpoint:${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/https-endpoint:${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/scheduler-endpoint:${{ github.sha }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        working-directory: terraform/
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform/
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/
        run: terraform plan -out ./plan.tfplan

      - name: Terraform Apply
        working-directory: terraform/
        run: terraform apply -auto-approve
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
